[[redirects]]
  # Serve a full size version
  from = "/images/full/*"
  to = "/.netlify/images?url=/images/:splat"
  status = 200

[[redirects]]
  # ...or serve a resized version
  from = "/images/:width/*"
  to = "/.netlify/images?url=/images/:splat&width=:width"
  status = 200